/-
Copyright (c) 2026 Nils Steuernagel. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Nils Steuernagel
-/
import FormalizingMastermind.decision_tree

/-!
# Generation of a Decision Tree Certificate based on Knuth's Algorithm

This files converts a `Tree` Object into strings and saves it in a new file as a
function called `KnuthsDecisionTree`.
-/

namespace Mastermind
namespace Knuth



namespace TreeFileGenerator

/--
Convert a Feedback object into a string
-/
def feedback_as_string (feedback : Feedback) : String :=
  s!"Result.from_counts {feedback.black_hits.val} {feedback.white_hits.val}"

/--
Convert a Tree object into a string
-/
partial def tree_as_string (tree : Tree) : String :=
  let children := tree.next_guesses.map fun (feedback, child) =>
    s!"\n    ({feedback_as_string feedback}, {tree_as_string child})"
  if children.isEmpty then
    "{ guess := to_StateNat46 " ++ toString tree.guess.val ++
      ", next_guesses := [] }"
  else
    "{ guess := to_StateNat46 " ++ toString tree.guess.val ++
      ", next_guesses := [" ++ String.intercalate "," children ++
      "\n  ] }"

/--
Converts a Tree object into a function represented as a string
-/
def renderModule (tree : Tree) : String :=
  "/-\n" ++
  "Copyright (c) 2026 Nils Steuernagel. All rights reserved.\n" ++
  "Released under Apache 2.0 license as described in the file LICENSE.\n" ++
  "Authors: Nils Steuernagel\n" ++
  "-/\n" ++
  --
  "import FormalizingMastermind.decision_tree\n\n" ++
  --
  "/-!\n" ++
  "# Certificate of a Decision Tree based on Knuth's Algorithm\n" ++
  "\n" ++
  "This function represents a Certificate of a Decision Tree. It holds a\n" ++
  "function called `KnuthsDecisionTree` which is a functional representation\n" ++
  "of the minimax calculation needed for finding a secret using Knuth's Algorithm.\n" ++
  "-/\n\n" ++
  --
  "set_option maxRecDepth 100000\n" ++
  "set_option maxHeartbeats 0\n" ++
  "namespace Mastermind\n" ++
  "namespace Knuth\n\n" ++
  --
  "/--\n" ++
  "The `Decision Tree` that was generated by `Tree.build_start` represented as\n" ++
  "a Lean definition.\n\n" ++
  "This is comparable to the Tree that Knuth showed in his paper.\n" ++
  "-/\n" ++
  "def KnuthsDecisionTree : Tree :=\n  " ++ tree_as_string tree ++ "\n\n" ++
  --
  "end Knuth\n" ++
  "end Mastermind\n"

/--
Generates a Decision Tree based on Knuth's Algorithm.
it concerts this Tree into a string and safes it as a function in
the file called `output_path`.
-/
def generate_file (output_path : System.FilePath) : IO Unit := do
  match Tree.start_build with
  | none =>
      throw <| IO.userError ("Tree.start_build did return `none. " ++
      "This should not happen, check the code and compare to earlier commits")
  | some tree =>
      IO.FS.writeFile output_path (renderModule tree)
      IO.println s!"wrote {output_path}"

end TreeFileGenerator
end Knuth
end Mastermind

def main :=
  Mastermind.Knuth.TreeFileGenerator.generate_file
    "FormalizingMastermind/generated_decision_tree.lean"
